services:
  - type: web
    name: olympic-sprinter-training
    env: python
    plan: free
    buildCommand: pip install -r req_temp.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1